# Generated by Django 3.2.6 on 2024-02-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_content', '0002_alter_content_site_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='site_logo',
            field=models.URLField(null=True),
        ),
    ]
